apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-monitor
  namespace: default
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      name: scaletestapp
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
    - default