http {
	# Настройка ограничений
    limit_req_zone $binary_remote_addr zone=api_rate_limit:10m rate=10r/m;

    # Настройка upstream для балансировки нагрузки
    upstream backend_servers {
        server backend1.example.com;
        server backend2.example.com;
        server backend3.example.com;
    }

    server {
        listen 80;

        location / {
            limit_req zone=api_rate_limit;

            # Возвращаем код 429
            limit_req_status 429;

            proxy_pass http://backend_servers;
        }

    }
}