apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scaletestapp
  name: scaletestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaletestapp
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
        - name: scaletestapp
          image: ghcr.io/yandex-practicum/scaletestapp
          resources:
            requests:
              memory: "10Mi"
            limits:
              memory: "30Mi"